# Generated by Django 3.1.2 on 2021-10-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A B', max_length=50)),
                ('email', models.CharField(default='a@a.com', max_length=50)),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='points.point')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='points.userdata')),
            ],
        ),
    ]
